name: Other Issue
description: Issues that are not bug reports or feature requests
title: "[Other issue]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        For general questions and design discussion, please use the Discussions page: https://github.com/open-rmf/rmf/discussions
        Not sure if this is the right repository? Open an issue on https://github.com/open-rmf/rmf
        For bug reports, please use the bug report issue form.
        For feature requests, please use the feature request issue form.
        Be as detailed about your issue as possible.

  - type: checkboxes
    id: checked-issues
    attributes:
      label: Before proceeding, is there an existing issue or discussion for this?
      options:
        - label: I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
