name: asan

on:
  pull_request:
  push:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  asan_test:
    name: rmf asan
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      dist-matrix: |
          [{"ros_distribution": "humble",
            "ubuntu_distribution": "jammy"}]
      # NOTE: Avoid adding comments in the package lines, this can break some of the called scripts in github actions
      packages: |
        <package_name_1>
        <package_name_2>
      asan: true